# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  publish = "out"

  # Default build command.
  command = "yarn build"

# [[plugins]]
#   package = "@sentry/netlify-build-plugin"
#   [plugins.inputs]
#     sentryOrg = ""
#     sentryProject = ""
